### PR TITLE
Patch ipython deps to set upper bound for jedi

### PR DESCRIPTION
**Pull request by chenghlee**
Fixes conda-forge/ipython-feedstock#127

### CODE REVIEW

**Review by pseudoyim — APPROVED** [review]
👍

**Comment by jakirkham** [comment]
Thanks Cheng! 😄

cc @h-vetinari (for vis)

**Comment by h-vetinari** [comment]
Thanks for doing this!

Just out of curiosity, the patch seems unconditional (as opposed to what I was guided to do in https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/113). I guess this will still work as long as the next `jedi 0.18`-compatible `ipython` version does not use the same dependency specification `jedi >=0.10` that's being replaced here.

**Comment by chenghlee** [comment]
That's correct; I took a sledgehammer-approach for this patch since it basically applies to all the ipython releases currently available in the defaults channel.

In any case, when the `jedi >=0.18`-compatible ipython version comes out, defaults will very likely specify 0.18 as the dependency lower bound, even if that ipython version is (or claims to be) compatible with jedi < 0.18. These changes in jedi seem significant enough that we'd want to avoid breaking other `jedi`-dependent software in the same environment.

**Pull request merged**
